server:
  port: 8280
spring:
  application:
    name: ZUUL-PROXY
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8260/eureka
zuul:
  routes:
    user-service: /user/**
  ignored-services: user-service
